import { Router } from 'express';
import { query } from './db';
import { requireAuth, requirePermission } from './authMiddleware';
const router=Router();
router.get('/workflow/service-requests',requireAuth,requirePermission('requests.view_all'),async(_req,res,next)=>{try{const r=await query('select * from service_requests where active=true order by created_at desc');res.json({data:r.rows})}catch(e){next(e)}});
router.get('/workflow/purchase-requests',requireAuth,requirePermission('requests.view_all'),async(_req,res,next)=>{try{const r=await query('select * from purchase_requests where active=true order by created_at desc');res.json({data:r.rows})}catch(e){next(e)}});
router.post('/workflow/service-requests/:id/status',requireAuth,requirePermission('requests.manage'),async(req,res,next)=>{try{const r=await query('select update_service_request_workflow($1,$2,$3,$4) data',[req.authUserId,req.params.id,String(req.body.status||''),req.body.note||null]);res.json({data:r.rows[0]?.data??null})}catch(e){next(e)}});
router.post('/workflow/purchase-requests/:id/status',requireAuth,requirePermission('requests.manage'),async(req,res,next)=>{try{const r=await query('select update_purchase_request_workflow($1,$2,$3,$4) data',[req.authUserId,req.params.id,String(req.body.status||''),req.body.note||null]);res.json({data:r.rows[0]?.data??null})}catch(e){next(e)}});
router.get('/workflow/users',requireAuth,requirePermission('users.view'),async(_req,res,next)=>{try{const r=await query('select * from v_active_profiles order by name');res.json({data:r.rows})}catch(e){next(e)}});
export default router;
