-- BIOTROP Gestão Industrial — PostgreSQL Core
-- Fonte oficial de dados da aplicação. Não depende de Supabase.
begin;
create extension if not exists pgcrypto;

create table if not exists app_users (id uuid primary key default gen_random_uuid(), name text not null, full_name text, username text unique, email text not null unique, password_hash text not null, phone text, department text, sector text, avatar_url text, active boolean not null default false, theme text not null default 'light', notifications_enabled boolean not null default true, last_login timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists roles (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, description text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists permissions (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, description text, resource text not null, action text not null, created_at timestamptz not null default now());
create table if not exists role_permissions (role_id uuid not null references roles(id) on delete cascade, permission_id uuid not null references permissions(id) on delete cascade, primary key(role_id,permission_id));
create table if not exists user_roles (user_id uuid not null references app_users(id) on delete cascade, role_id uuid not null references roles(id) on delete restrict, active boolean not null default true, assigned_by uuid references app_users(id) on delete set null, assigned_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(user_id,role_id));
create unique index if not exists ux_user_roles_one_active on user_roles(user_id) where active;
create table if not exists sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references app_users(id) on delete cascade, token_hash text unique not null, created_at timestamptz not null default now(), expires_at timestamptz not null, last_seen_at timestamptz not null default now(), user_agent text, ip_address inet);
create index if not exists idx_sessions_user_exp on sessions(user_id,expires_at);
create table if not exists password_reset_tokens (id uuid primary key default gen_random_uuid(), user_id uuid not null references app_users(id) on delete cascade, token_hash text unique not null, created_at timestamptz not null default now(), expires_at timestamptz not null, used_at timestamptz);

create table if not exists industrial_units (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, sort_order integer not null default 0, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists utility_meters (id uuid primary key default gen_random_uuid(), unit_id uuid references industrial_units(id), code text unique not null, name text not null, utility_type text not null check(utility_type in ('agua','gas','energia','horimetro')), location text, unit text not null, initial_reading numeric(18,3), active boolean not null default true, created_by uuid references app_users(id), updated_by uuid references app_users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_meters_unit_type on utility_meters(unit_id,utility_type,active);
create table if not exists file_objects (id uuid primary key default gen_random_uuid(), owner_id uuid references app_users(id) on delete set null, bucket text not null default 'private', object_name text not null, original_name text not null, mime_type text not null, size_bytes bigint not null check(size_bytes>=0), content bytea not null, sha256 text not null, created_at timestamptz not null default now(), unique(bucket,object_name));
create table if not exists utility_readings (id uuid primary key default gen_random_uuid(), meter_id uuid not null references utility_meters(id), reading_value numeric(18,3) not null check(reading_value>=0), previous_reading numeric(18,3), consumption numeric(18,3), observation text, photo_file_id uuid references file_objects(id), latitude numeric(10,7), longitude numeric(10,7), status text not null default 'registrado' check(status in ('registrado','corrigir','cancelado')), created_by uuid not null references app_users(id), server_timestamp timestamptz not null default now(), created_at timestamptz not null default now());
create index if not exists idx_readings_meter_date on utility_readings(meter_id,server_timestamp desc);

create table if not exists material_families (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, fields jsonb not null default '[]'::jsonb, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists service_requests (id uuid primary key default gen_random_uuid(), request_number text unique not null, requester_id uuid not null references app_users(id), material_type_id uuid references material_families(id), description text not null, justification text, dynamic_fields jsonb not null default '{}'::jsonb, links jsonb not null default '[]'::jsonb, photos jsonb not null default '[]'::jsonb, status text not null default 'ENVIADA', warehouse_note text, process_number text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists purchase_requests (id uuid primary key default gen_random_uuid(), code text unique not null, requester_id uuid not null references app_users(id), team text, urgency text, cost_center text, description text not null, justification text, approval_note text, items jsonb not null default '[]'::jsonb, attachments jsonb not null default '[]'::jsonb, links jsonb not null default '[]'::jsonb, status text not null default 'PENDENTE', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists approval_leaders (workflow text primary key, leader_user_id uuid not null references app_users(id), updated_by uuid references app_users(id) on delete set null, updated_at timestamptz not null default now());

create table if not exists training_courses (id uuid primary key default gen_random_uuid(), code text unique, title text not null, description text, category text, audience_groups jsonb not null default '[]'::jsonb, content jsonb not null default '[]'::jsonb, quiz jsonb not null default '[]'::jsonb, video_file_id uuid references file_objects(id), validity_months integer, passing_score numeric(5,2), version text not null default '1.0', mandatory boolean not null default false, active boolean not null default true, created_by uuid references app_users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists training_paths (id uuid primary key default gen_random_uuid(), code text unique, name text not null, description text, audience_groups jsonb not null default '[]'::jsonb, due_days integer, validity_months integer, active boolean not null default true, responsible_id uuid references app_users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists training_path_items (path_id uuid not null references training_paths(id) on delete cascade, course_id uuid not null references training_courses(id), sort_order integer not null, primary key(path_id,course_id), unique(path_id,sort_order));
create table if not exists training_progress (id uuid primary key default gen_random_uuid(), user_id uuid not null references app_users(id) on delete cascade, course_id uuid not null references training_courses(id), path_id uuid references training_paths(id) on delete set null, assigned_at timestamptz not null default now(), due_at timestamptz, started_at timestamptz, completed_at timestamptz, expires_at timestamptz, score numeric(5,2), status text not null default 'assigned' check(status in ('assigned','in_progress','completed','overdue','failed','cancelled')), certificate_file_id uuid references file_objects(id), metadata jsonb not null default '{}'::jsonb, unique(user_id,course_id,path_id));
create index if not exists idx_training_progress_user_status on training_progress(user_id,status);
create table if not exists audit_logs (id bigserial primary key, user_id uuid references app_users(id) on delete set null, action text not null, resource text not null, resource_id text, before_data jsonb, after_data jsonb, ip_address inet, user_agent text, created_at timestamptz not null default now());

insert into roles(code,name,description) values ('super_admin','Super administrador','Acesso integral'),('administrador','Administrador','Gestão operacional e usuários'),('pcm','PCM','Planejamento e controle'),('almoxarife','Almoxarife','Materiais e solicitações'),('tecnico','Técnico','Operação e apontamentos'),('viewer','Viewer','Acesso mínimo') on conflict(code) do update set name=excluded.name,description=excluded.description,active=true,updated_at=now();
insert into permissions(code,name,description,resource,action) values ('users.view','Consultar usuários','Consultar usuários','users','view'),('users.manage','Gerenciar usuários','Ativar e alterar perfil','users','manage'),('roles.view','Consultar perfis','Consultar RBAC','roles','view'),('roles.manage','Gerenciar perfis','Gerenciar RBAC','roles','manage'),('meters.view','Consultar medidores','Consultar medidores','meters','view'),('meters.manage','Gerenciar medidores','Gerenciar medidores','meters','manage'),('readings.create','Registrar leituras','Registrar apontamentos','readings','create'),('readings.view_own','Consultar próprias leituras','Histórico próprio','readings','view_own'),('readings.view_all','Consultar todas as leituras','Histórico completo','readings','view_all'),('readings.manage','Gerenciar leituras','Corrigir leituras','readings','manage'),('requests.create','Criar solicitações','Criar SCI/SCM','requests','create'),('requests.view_own','Consultar próprias solicitações','Solicitações próprias','requests','view_own'),('requests.view_all','Consultar solicitações','Solicitações gerais','requests','view_all'),('requests.approve','Aprovar solicitações','Aprovar/reprovar','requests','approve'),('requests.manage','Gerenciar solicitações','Gerenciar fluxos','requests','manage'),('reports.view','Consultar relatórios','Indicadores','reports','view'),('audit.view','Consultar auditoria','Trilha de auditoria','audit','view'),('trainings.view','Consultar treinamentos','Cursos e progresso','trainings','view'),('trainings.manage','Gerenciar treinamentos','Trilhas e quizzes','trainings','manage') on conflict(code) do update set name=excluded.name,description=excluded.description,resource=excluded.resource,action=excluded.action;
insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r cross join permissions p where r.code='super_admin' on conflict do nothing;
insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r join permissions p on p.code=any(array['users.view','users.manage','roles.view','roles.manage','meters.view','meters.manage','readings.create','readings.view_own','readings.view_all','readings.manage','requests.create','requests.view_own','requests.view_all','requests.approve','requests.manage','reports.view','audit.view','trainings.view','trainings.manage']) where r.code='administrador' on conflict do nothing;
insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r join permissions p on p.code=any(array['meters.view','readings.create','readings.view_own','readings.view_all','requests.create','requests.view_own','requests.view_all','reports.view','trainings.view']) where r.code='pcm' on conflict do nothing;
insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r join permissions p on p.code=any(array['requests.create','requests.view_own','requests.view_all','requests.approve','requests.manage','reports.view','trainings.view']) where r.code='almoxarife' on conflict do nothing;
insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r join permissions p on p.code=any(array['meters.view','readings.create','readings.view_own','requests.create','requests.view_own','trainings.view']) where r.code='tecnico' on conflict do nothing;
insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r join permissions p on p.code='trainings.view' where r.code='viewer' on conflict do nothing;

insert into industrial_units(code,name,sort_order) values ('CAMM1','CAMM 1',10),('CAMM2','CAMM 2',20),('CAMM3','CAMM 3',30),('CLOG','C. LOG',40) on conflict(code) do update set name=excluded.name,sort_order=excluded.sort_order,active=true,updated_at=now();

create or replace function set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=clock_timestamp(); return new; end; $$;
do $$ declare t text; begin foreach t in array['app_users','roles','industrial_units','utility_meters','material_families','service_requests','purchase_requests','training_courses','training_paths'] loop execute format('drop trigger if exists trg_%s_updated_at on %I',t,t); execute format('create trigger trg_%s_updated_at before update on %I for each row execute function set_updated_at()',t,t); end loop; end $$;
create or replace function has_permission(p_user_id uuid,p_permission_code text) returns boolean language sql stable as $$ select exists(select 1 from user_roles ur join roles r on r.id=ur.role_id join role_permissions rp on rp.role_id=r.id join permissions p on p.id=rp.permission_id join app_users u on u.id=ur.user_id where ur.user_id=p_user_id and ur.active and r.active and p.code=p_permission_code and u.active); $$;
create or replace function get_user_access_context(p_user_id uuid) returns jsonb language sql stable as $$ select jsonb_build_object('user_id',u.id,'profile',jsonb_build_object('id',u.id,'name',u.name,'full_name',u.full_name,'username',u.username,'email',u.email,'phone',u.phone,'department',u.department,'sector',u.sector,'avatar_url',u.avatar_url,'active',u.active,'theme',u.theme,'notifications_enabled',u.notifications_enabled),'roles',coalesce((select jsonb_agg(jsonb_build_object('code',r.code,'name',r.name)) from user_roles ur join roles r on r.id=ur.role_id where ur.user_id=u.id and ur.active and r.active),'[]'::jsonb),'permissions',coalesce((select jsonb_agg(distinct p.code) from user_roles ur join roles r on r.id=ur.role_id join role_permissions rp on rp.role_id=r.id join permissions p on p.id=rp.permission_id where ur.user_id=u.id and ur.active and r.active),'[]'::jsonb)) from app_users u where u.id=p_user_id; $$;
create or replace function create_utility_reading(p_meter_id uuid,p_reading_value numeric,p_observation text default null,p_photo_file_id uuid default null,p_latitude numeric default null,p_longitude numeric default null,p_user_id uuid default null) returns jsonb language plpgsql as $$ declare prev numeric; x utility_readings; begin if p_user_id is null or not has_permission(p_user_id,'readings.create') then raise exception 'Permissão negada'; end if; select reading_value into prev from utility_readings where meter_id=p_meter_id and status='registrado' order by server_timestamp desc limit 1; if prev is not null and p_reading_value<prev then raise exception 'A leitura não pode ser menor que a anterior'; end if; if p_photo_file_id is null then raise exception 'Evidência fotográfica obrigatória'; end if; insert into utility_readings(meter_id,reading_value,previous_reading,consumption,observation,photo_file_id,latitude,longitude,created_by) values(p_meter_id,p_reading_value,prev,case when prev is null then null else p_reading_value-prev end,p_observation,p_photo_file_id,p_latitude,p_longitude,p_user_id) returning * into x; return to_jsonb(x); end $$;
create or replace function admin_set_user_access(p_admin_id uuid,p_user_id uuid,p_role_code text,p_active boolean) returns jsonb language plpgsql as $$ declare rid uuid; x app_users; begin if not has_permission(p_admin_id,'users.manage') then raise exception 'Permissão negada'; end if; select id into rid from roles where code=p_role_code and active; if rid is null then raise exception 'Perfil inválido'; end if; update app_users set active=p_active where id=p_user_id returning * into x; if not found then raise exception 'Usuário não encontrado'; end if; update user_roles set active=false where user_id=p_user_id; insert into user_roles(user_id,role_id,active,assigned_by) values(p_user_id,rid,true,p_admin_id) on conflict(user_id,role_id) do update set active=true,assigned_by=excluded.assigned_by,updated_at=now(); insert into audit_logs(user_id,action,resource,resource_id,after_data) values(p_admin_id,'access.change','app_users',p_user_id::text,to_jsonb(x)); return to_jsonb(x); end $$;
create or replace function update_service_request_workflow(p_actor uuid,p_request_id uuid,p_status text,p_note text default null) returns jsonb language plpgsql as $$ declare x service_requests; begin if not has_permission(p_actor,'requests.manage') then raise exception 'Permissão negada'; end if; update service_requests set status=upper(p_status),warehouse_note=coalesce(p_note,warehouse_note) where id=p_request_id returning * into x; if not found then raise exception 'Solicitação não encontrada'; end if; insert into audit_logs(user_id,action,resource,resource_id,after_data) values(p_actor,'status.change','service_requests',p_request_id::text,to_jsonb(x)); return to_jsonb(x); end $$;
create or replace function update_purchase_request_workflow(p_actor uuid,p_request_id uuid,p_status text,p_note text default null) returns jsonb language plpgsql as $$ declare x purchase_requests; begin if not has_permission(p_actor,'requests.manage') then raise exception 'Permissão negada'; end if; update purchase_requests set status=upper(p_status),approval_note=coalesce(p_note,approval_note) where id=p_request_id returning * into x; if not found then raise exception 'Solicitação não encontrada'; end if; insert into audit_logs(user_id,action,resource,resource_id,after_data) values(p_actor,'status.change','purchase_requests',p_request_id::text,to_jsonb(x)); return to_jsonb(x); end $$;
create or replace view v_active_profiles as select u.id,u.name,u.full_name,u.email,u.department,u.sector,u.avatar_url,u.active,coalesce(r.code,'viewer') role_code from app_users u left join lateral(select r.code from user_roles ur join roles r on r.id=ur.role_id where ur.user_id=u.id and ur.active and r.active limit 1) r on true where u.active;
create or replace view v_utility_meter_status as select m.id,m.code,m.name,m.utility_type,m.location,m.unit,m.unit_id,m.active,iu.code unit_code,iu.name unit_name,lr.reading_value last_reading,lr.consumption last_consumption,lr.server_timestamp last_reading_at,lr.created_by last_reading_user_id,u.name last_user_name from utility_meters m left join industrial_units iu on iu.id=m.unit_id left join lateral(select r.* from utility_readings r where r.meter_id=m.id and r.status='registrado' order by r.server_timestamp desc limit 1) lr on true left join app_users u on u.id=lr.created_by;
commit;
