-- BIOTROP V2: líderes de aprovação + notificações
create table if not exists public.approval_leaders (workflow text primary key check (workflow in ('SCI','SCM')), leader_user_id uuid not null references public.profiles(id) on delete restrict, updated_by uuid references public.profiles(id), updated_at timestamptz not null default now());
create table if not exists public.app_notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, type text not null default 'info', title text not null, body text, entity_type text, entity_id uuid, read_at timestamptz, created_at timestamptz not null default now());
create index if not exists idx_app_notifications_user_unread on public.app_notifications(user_id,read_at,created_at desc);
alter table public.approval_leaders enable row level security; alter table public.app_notifications enable row level security;
drop policy if exists approval_leaders_select on public.approval_leaders; create policy approval_leaders_select on public.approval_leaders for select to authenticated using (true);
drop policy if exists approval_leaders_write on public.approval_leaders; create policy approval_leaders_write on public.approval_leaders for all to authenticated using (coalesce((select app_role from public.profiles where id=auth.uid()),'') in ('super_admin','pcm','almoxarife')) with check (coalesce((select app_role from public.profiles where id=auth.uid()),'') in ('super_admin','pcm','almoxarife'));
drop policy if exists app_notifications_select on public.app_notifications; create policy app_notifications_select on public.app_notifications for select to authenticated using (user_id=auth.uid());
drop policy if exists app_notifications_update on public.app_notifications; create policy app_notifications_update on public.app_notifications for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create or replace function public.set_approval_leader(p_workflow text,p_leader uuid) returns public.approval_leaders language plpgsql security definer set search_path=public as $$ declare v public.approval_leaders; begin if lower(coalesce((select app_role from public.profiles where id=auth.uid()),'')) not in ('super_admin','pcm','almoxarife') then raise exception 'Sem permissão para configurar líderes'; end if; if not exists(select 1 from profiles where id=p_leader and coalesce(active,is_active,true)) then raise exception 'Usuário líder inválido ou inativo'; end if; insert into approval_leaders(workflow,leader_user_id,updated_by,updated_at) values(upper(p_workflow),p_leader,auth.uid(),now()) on conflict(workflow) do update set leader_user_id=excluded.leader_user_id,updated_by=auth.uid(),updated_at=now() returning * into v; return v; end; $$;
grant execute on function public.set_approval_leader(text,uuid) to authenticated;
create or replace function public.is_workflow_leader(p_workflow text,p_user uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from approval_leaders where workflow=upper(p_workflow) and leader_user_id=p_user) or exists(select 1 from profiles where id=p_user and app_role in ('super_admin','pcm','almoxarife')); $$;
grant execute on function public.is_workflow_leader(text,uuid) to authenticated;
create or replace function public.approval_status_guard() returns trigger language plpgsql security definer set search_path=public as $$ declare v_workflow text; begin v_workflow=case when TG_TABLE_NAME='service_requests' then 'SCI' else 'SCM' end; if (new.status is distinct from old.status or new.approved_by is distinct from old.approved_by or new.approved_at is distinct from old.approved_at) and not public.is_workflow_leader(v_workflow,auth.uid()) then raise exception 'Aprovação restrita ao líder de %',v_workflow; end if; return new; end; $$;
drop trigger if exists trg_service_request_approval_guard on public.service_requests; create trigger trg_service_request_approval_guard before update on public.service_requests for each row execute function public.approval_status_guard();
drop trigger if exists trg_purchase_request_approval_guard on public.purchase_requests; create trigger trg_purchase_request_approval_guard before update on public.purchase_requests for each row execute function public.approval_status_guard();
create or replace function public.notify_workflow_request() returns trigger language plpgsql security definer set search_path=public as $$ declare v_workflow text; v_leader uuid; v_title text; v_code text; begin v_workflow=case when TG_TABLE_NAME='service_requests' then 'SCI' else 'SCM' end; v_leader=(select leader_user_id from approval_leaders where workflow=v_workflow); v_code=coalesce(new.request_number,new.code,'Solicitação'); if v_leader is not null then v_title='Nova '||v_workflow||' para aprovação'; insert into app_notifications(user_id,type,title,body,entity_type,entity_id) values(v_leader,'approval',v_title,v_code||' aguarda sua análise.',v_workflow,new.id); insert into notification_email_queue(event_type,entity_type,entity_id,recipient_email,recipient_name,subject,body_text,status) select 'approval_pending',v_workflow,new.id,p.email,p.name,v_title,v_code||' aguarda sua análise.','pending' from profiles p where p.id=v_leader and p.email is not null; end if; return new; end; $$;
drop trigger if exists trg_service_request_notify on public.service_requests; create trigger trg_service_request_notify after insert on public.service_requests for each row execute function public.notify_workflow_request();
drop trigger if exists trg_purchase_request_notify on public.purchase_requests; create trigger trg_purchase_request_notify after insert on public.purchase_requests for each row execute function public.notify_workflow_request();
